"""Prompts for the deep research agent."""

from .prompts import (
    CLARIFY_SYSTEM_PROMPT,
    DECIDE_SYSTEM_PROMPT,
    GENERATE_QUERIES_SYSTEM_PROMPT,
    GENERATE_REPORT_SYSTEM_PROMPT,
    RESEARCH_BRIEF_SYSTEM_PROMPT,
)

__all__ = [
    "CLARIFY_SYSTEM_PROMPT",
    "RESEARCH_BRIEF_SYSTEM_PROMPT",
    "GENERATE_QUERIES_SYSTEM_PROMPT",
    "DECIDE_SYSTEM_PROMPT",
    "GENERATE_REPORT_SYSTEM_PROMPT",
]

